// Generated by tools/extract_tokens.py from source/Bridge_RC2_1.html
// Bridge RC2.1 · do not edit by hand; re-run `tools/extract_all.sh` instead.
// The prototype is the canon. This file is its shadow.

import SwiftUI

/// The Bridge palette, generated from the prototype's `:root` block.
///
/// Every colour resolves through the asset catalog rather than a literal, so
/// a future light appearance is a catalog change and not a code change.
public enum Theme {
    // MARK: Colour

    /// The page ground behind every screen.  `#111114`
    public static let bg = Color("bg", bundle: .module)

    /// Cards, the sidebar, raised panels.  `#1d1d21`
    public static let surface = Color("surface", bundle: .module)

    /// A panel raised above a card; table header rows.  `#26262b`
    public static let surface2 = Color("surface2", bundle: .module)

    /// Text fields, selects, the inside of a control.  `#2c2c31`
    public static let input = Color("input", bundle: .module)

    /// Hairlines, card borders, table rules.  `#33333a`
    public static let line = Color("line", bundle: .module)

    /// Primary copy.  `#ffffff`
    public static let text = Color("text", bundle: .module)

    /// Secondary copy; labels above values.  `#c9c9ce`
    public static let text2 = Color("text2", bundle: .module)

    /// Tertiary copy; captions, timestamps, disabled states.  `#8e8e93`
    public static let muted = Color("muted", bundle: .module)

    /// The deep green behind primary buttons.  `#0b7a4b`
    public static let accent = Color("accent", bundle: .module)

    /// The live green: healthy status, links, focus rings, most icons.  `#3fcf8e`
    public static let led = Color("led", bundle: .module)

    /// The lime power path: energy, the spine, the Bridge mark.  `#9ef01a`
    public static let power = Color("power", bundle: .module)

    /// Amber: a clock running down, a node too warm.  `#fac775`
    public static let warn = Color("warn", bundle: .module)

    /// Red: a broken seal, a node down, a failed check.  `#e5484d`
    public static let crit = Color("crit", bundle: .module)

    /// Blue: informational chips, neutral annotations.  `#6aa9ff`
    public static let info = Color("info", bundle: .module)

    // MARK: Metrics

    /// `18px` in the prototype.
    public static let radiusCard: CGFloat = 18

    /// `10px` in the prototype.
    public static let radiusCtl: CGFloat = 10

    /// `16px` in the prototype.
    public static let gap: CGFloat = 16

    // MARK: Type

    /// The prototype's body size. Treated as the Dynamic Type base rather than a fixed
    /// point size — see the conversion plan, section 7.
    public static let bodyPointSize: CGFloat = 15

    /// The prototype's `--mono` stack resolves to SF Mono on Apple platforms.
    public static let mono = Font.system(.body, design: .monospaced)
}
