// Generated by tools/extract_icons.py from source/Bridge_RC2_1.html
// Bridge RC2.1 · do not edit by hand; re-run `tools/extract_all.sh` instead.
// The prototype is the canon. This file is its shadow.


import SwiftUI

/// The route glyphs, ported as geometry.
///
/// These are a deliberate monoline family and carry the branding, so they are
/// not swapped for SF Symbols. Drawn as paths rather than shipped as SVG assets
/// so that `var(--led)` stays `Theme.led` and the set follows the palette.
public struct BridgeIcon: View {
    public let screen: Screen
    public var size: CGFloat = 40

    public init(_ screen: Screen, size: CGFloat = 40) {
        self.screen = screen
        self.size = size
    }

    public var body: some View {
        Canvas { context, bounds in
            let geometry = Self.geometry(for: screen)
            let s = min(bounds.width, bounds.height) / geometry.side
            let transform = CGAffineTransform(scaleX: s, y: s)
            for layer in geometry.layers {
                let path = layer.path.applying(transform)
                if let fill = layer.fill {
                    context.fill(path, with: .color(fill))
                }
                if let stroke = layer.stroke {
                    context.stroke(path, with: .color(stroke),
                                   style: StrokeStyle(lineWidth: layer.width * s,
                                                      lineCap: layer.cap,
                                                      lineJoin: layer.join))
                }
            }
        }
        .frame(width: size, height: size)
        .accessibilityHidden(true)
    }

    struct Layer {
        var path: Path
        var stroke: Color?
        var fill: Color?
        var width: CGFloat
        var cap: CGLineCap = .butt
        var join: CGLineJoin = .miter
    }

    /// The glyphs are drawn on a 48-unit square; the marks on 64.
    static func geometry(for screen: Screen) -> (side: CGFloat, layers: [Layer]) {
        switch screen {
        case .cobranza: (48, [
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 9, y: 9, width: 30, height: 30))
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 24, y: 15))
            p.addLine(to: CGPoint(x: 24, y: 33))
            p.move(to: CGPoint(x: 19, y: 20))
            p.addCurve(to: CGPoint(x: 29, y: 20), control1: CGPoint(x: 19, y: 17), control2: CGPoint(x: 29, y: 17))
            p.addCurve(to: CGPoint(x: 19, y: 28), control1: CGPoint(x: 29, y: 24), control2: CGPoint(x: 19, y: 24))
            p.addCurve(to: CGPoint(x: 29, y: 28), control1: CGPoint(x: 19, y: 31), control2: CGPoint(x: 29, y: 31))
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .round,
                  join: .miter),
        ])
        case .facturas: (48, [
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 12, y: 6))
            p.addLine(to: CGPoint(x: 30, y: 6))
            p.addLine(to: CGPoint(x: 38, y: 14))
            p.addLine(to: CGPoint(x: 38, y: 42))
            p.addLine(to: CGPoint(x: 12, y: 42))
            p.closeSubpath()
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 30, y: 6))
            p.addLine(to: CGPoint(x: 30, y: 14))
            p.addLine(to: CGPoint(x: 38, y: 14))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 17, y: 22))
            p.addLine(to: CGPoint(x: 33, y: 22))
            p.move(to: CGPoint(x: 17, y: 28))
            p.addLine(to: CGPoint(x: 33, y: 28))
            p.move(to: CGPoint(x: 17, y: 34))
            p.addLine(to: CGPoint(x: 27, y: 34))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .round,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 28, y: 31, width: 10, height: 10))
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
        ])
        case .agentes: (48, [
            Layer(path: Path { p in
            p.addRoundedRect(in: CGRect(x: 8, y: 14, width: 32, height: 24), cornerSize: CGSize(width: 7, height: 7))
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 15, y: 23, width: 6, height: 6))
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 27, y: 23, width: 6, height: 6))
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 18, y: 33))
            p.addQuadCurve(to: CGPoint(x: 30, y: 33), control: CGPoint(x: 24, y: 37))
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2,
                  cap: .round,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 24, y: 14))
            p.addLine(to: CGPoint(x: 24, y: 7))
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 22, y: 4, width: 4, height: 4))
            },
                  stroke: nil,
                  fill: Theme.power,
                  width: 1,
                  cap: .butt,
                  join: .miter),
        ])
        case .modelos: (48, [
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 24, y: 8))
            p.addLine(to: CGPoint(x: 42, y: 17))
            p.addLine(to: CGPoint(x: 24, y: 26))
            p.addLine(to: CGPoint(x: 6, y: 17))
            p.closeSubpath()
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .round),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 6, y: 25))
            p.addLine(to: CGPoint(x: 24, y: 34))
            p.addLine(to: CGPoint(x: 42, y: 25))
            p.move(to: CGPoint(x: 6, y: 33))
            p.addLine(to: CGPoint(x: 24, y: 42))
            p.addLine(to: CGPoint(x: 42, y: 33))
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .round),
        ])
        case .catalogo: (48, [
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 24, y: 6))
            p.addLine(to: CGPoint(x: 27, y: 14))
            p.addLine(to: CGPoint(x: 35, y: 17))
            p.addLine(to: CGPoint(x: 27, y: 20))
            p.addLine(to: CGPoint(x: 24, y: 28))
            p.addLine(to: CGPoint(x: 21, y: 20))
            p.addLine(to: CGPoint(x: 13, y: 17))
            p.addLine(to: CGPoint(x: 21, y: 14))
            p.closeSubpath()
            },
                  stroke: nil,
                  fill: Theme.power,
                  width: 1,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 10, y: 34))
            p.addLine(to: CGPoint(x: 11.5, y: 38))
            p.addLine(to: CGPoint(x: 15.5, y: 39.5))
            p.addLine(to: CGPoint(x: 11.5, y: 41))
            p.addLine(to: CGPoint(x: 10, y: 45))
            p.addLine(to: CGPoint(x: 8.5, y: 41))
            p.addLine(to: CGPoint(x: 4.5, y: 39.5))
            p.addLine(to: CGPoint(x: 8.5, y: 38))
            p.closeSubpath()
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 36, y: 30))
            p.addLine(to: CGPoint(x: 38, y: 35))
            p.addLine(to: CGPoint(x: 43, y: 37))
            p.addLine(to: CGPoint(x: 38, y: 39))
            p.addLine(to: CGPoint(x: 36, y: 44))
            p.addLine(to: CGPoint(x: 34, y: 39))
            p.addLine(to: CGPoint(x: 29, y: 37))
            p.addLine(to: CGPoint(x: 34, y: 35))
            p.closeSubpath()
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
        ])
        case .configuracion: (48, [
            Layer(path: Path { p in
            p.addRoundedRect(in: CGRect(x: 10, y: 8, width: 28, height: 10), cornerSize: CGSize(width: 3, height: 3))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addRoundedRect(in: CGRect(x: 10, y: 20, width: 28, height: 10), cornerSize: CGSize(width: 3, height: 3))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addRoundedRect(in: CGRect(x: 10, y: 32, width: 28, height: 10), cornerSize: CGSize(width: 3, height: 3))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 14.2, y: 11.2, width: 3.6, height: 3.6))
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 14.2, y: 23.2, width: 3.6, height: 3.6))
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 14.2, y: 35.2, width: 3.6, height: 3.6))
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
        ])
        case .cadena: (48, [
            Layer(path: Path { p in
            p.addRoundedRect(in: CGRect(x: 5, y: 18, width: 18, height: 12), cornerSize: CGSize(width: 6, height: 6))
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addRoundedRect(in: CGRect(x: 25, y: 18, width: 18, height: 12), cornerSize: CGSize(width: 6, height: 6))
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 18, y: 24))
            p.addLine(to: CGPoint(x: 30, y: 24))
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 21, y: 5, width: 6, height: 6))
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 21, y: 37, width: 6, height: 6))
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
        ])
        case .datos: (48, [
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 10, y: 7, width: 28, height: 10))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 10, y: 12))
            p.addLine(to: CGPoint(x: 10, y: 36))
            p.addSVGArc(from: CGPoint(x: 10, y: 36), to: CGPoint(x: 38, y: 36), rx: 14, ry: 5, rotation: 0, largeArc: false, sweep: false)
            p.addLine(to: CGPoint(x: 38, y: 12))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 10, y: 24))
            p.addSVGArc(from: CGPoint(x: 10, y: 24), to: CGPoint(x: 38, y: 24), rx: 14, ry: 5, rotation: 0, largeArc: false, sweep: false)
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
        ])
        case .salud: (48, [
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 6, y: 26))
            p.addLine(to: CGPoint(x: 14, y: 26))
            p.addLine(to: CGPoint(x: 18, y: 14))
            p.addLine(to: CGPoint(x: 24, y: 36))
            p.addLine(to: CGPoint(x: 30, y: 20))
            p.addLine(to: CGPoint(x: 34, y: 26))
            p.addLine(to: CGPoint(x: 42, y: 26))
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .round,
                  join: .round),
        ])
        case .energia: (48, [
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 10, y: 10, width: 12, height: 12))
            },
                  stroke: nil,
                  fill: Theme.power,
                  width: 1,
                  cap: .butt,
                  join: .miter),
        ])
        case .integraciones: (48, [
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 16, y: 10))
            p.addLine(to: CGPoint(x: 16, y: 20))
            p.move(to: CGPoint(x: 32, y: 10))
            p.addLine(to: CGPoint(x: 32, y: 20))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 3,
                  cap: .round,
                  join: .miter),
            Layer(path: Path { p in
            p.addRoundedRect(in: CGRect(x: 10, y: 20, width: 28, height: 12), cornerSize: CGSize(width: 4, height: 4))
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 24, y: 32))
            p.addLine(to: CGPoint(x: 24, y: 40))
            },
                  stroke: Theme.power,
                  fill: nil,
                  width: 3,
                  cap: .round,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 21.5, y: 39.5, width: 5, height: 5))
            },
                  stroke: nil,
                  fill: Theme.power,
                  width: 1,
                  cap: .butt,
                  join: .miter),
        ])
        case .ajustes: (48, [
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 8, y: 14))
            p.addLine(to: CGPoint(x: 40, y: 14))
            p.move(to: CGPoint(x: 8, y: 24))
            p.addLine(to: CGPoint(x: 40, y: 24))
            p.move(to: CGPoint(x: 8, y: 34))
            p.addLine(to: CGPoint(x: 40, y: 34))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .round,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 14, y: 10, width: 8, height: 8))
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 26, y: 20, width: 8, height: 8))
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 10, y: 30, width: 8, height: 8))
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
        ])
        case .incidentes: (48, [
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 12, y: 30))
            p.addLine(to: CGPoint(x: 12, y: 22))
            p.addSVGArc(from: CGPoint(x: 12, y: 22), to: CGPoint(x: 36, y: 22), rx: 12, ry: 12, rotation: 0, largeArc: false, sweep: true)
            p.addLine(to: CGPoint(x: 36, y: 30))
            p.addLine(to: CGPoint(x: 40, y: 34))
            p.addLine(to: CGPoint(x: 8, y: 34))
            p.closeSubpath()
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .round),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 20, y: 38))
            p.addSVGArc(from: CGPoint(x: 20, y: 38), to: CGPoint(x: 28, y: 38), rx: 4, ry: 4, rotation: 0, largeArc: false, sweep: false)
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 31, y: 7, width: 10, height: 10))
            },
                  stroke: nil,
                  fill: Theme.crit,
                  width: 1,
                  cap: .butt,
                  join: .miter),
        ])
        case .actualizar: (48, [
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 36, y: 20))
            p.addSVGArc(from: CGPoint(x: 36, y: 20), to: CGPoint(x: 38, y: 28), rx: 13, ry: 13, rotation: 0, largeArc: true, sweep: false)
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .round,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 38, y: 12))
            p.addLine(to: CGPoint(x: 38, y: 21))
            p.addLine(to: CGPoint(x: 29, y: 21))
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .round,
                  join: .round),
        ])
        case .auditoria: (48, [
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 10, y: 10, width: 22, height: 22))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 29, y: 29))
            p.addLine(to: CGPoint(x: 40, y: 40))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 3,
                  cap: .round,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 15, y: 21))
            p.addLine(to: CGPoint(x: 19, y: 25))
            p.addLine(to: CGPoint(x: 27, y: 17))
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .round,
                  join: .round),
        ])
        case .conciliacion: (48, [
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 24, y: 8))
            p.addLine(to: CGPoint(x: 24, y: 40))
            p.move(to: CGPoint(x: 10, y: 16))
            p.addLine(to: CGPoint(x: 38, y: 16))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .round,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 10, y: 16))
            p.addLine(to: CGPoint(x: 4, y: 30))
            p.addLine(to: CGPoint(x: 16, y: 30))
            p.closeSubpath()
            p.move(to: CGPoint(x: 38, y: 16))
            p.addLine(to: CGPoint(x: 32, y: 30))
            p.addLine(to: CGPoint(x: 44, y: 30))
            p.closeSubpath()
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .round),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 16, y: 40))
            p.addLine(to: CGPoint(x: 32, y: 40))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .round,
                  join: .miter),
        ])
        case .medidas: (48, [
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 8, y: 34))
            p.addSVGArc(from: CGPoint(x: 8, y: 34), to: CGPoint(x: 40, y: 34), rx: 16, ry: 16, rotation: 0, largeArc: false, sweep: true)
            },
                  stroke: Theme.surface2,
                  fill: nil,
                  width: 6,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 8, y: 34))
            p.addSVGArc(from: CGPoint(x: 8, y: 34), to: CGPoint(x: 30, y: 19), rx: 16, ry: 16, rotation: 0, largeArc: false, sweep: true)
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 6,
                  cap: .round,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 24, y: 34))
            p.addLine(to: CGPoint(x: 33, y: 22))
            },
                  stroke: Theme.text,
                  fill: nil,
                  width: 2.5,
                  cap: .round,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 21, y: 31, width: 6, height: 6))
            },
                  stroke: nil,
                  fill: Theme.text,
                  width: 1,
                  cap: .butt,
                  join: .miter),
        ])
        case .tiendas: (48, [
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 8, y: 20))
            p.addLine(to: CGPoint(x: 12, y: 8))
            p.addLine(to: CGPoint(x: 36, y: 8))
            p.addLine(to: CGPoint(x: 40, y: 20))
            p.closeSubpath()
            },
                  stroke: Theme.text2,
                  fill: Theme.surface2,
                  width: 2.5,
                  cap: .butt,
                  join: .round),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 10, y: 20))
            p.addLine(to: CGPoint(x: 10, y: 40))
            p.addLine(to: CGPoint(x: 38, y: 40))
            p.addLine(to: CGPoint(x: 38, y: 20))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addRect(CGRect(x: 20, y: 28, width: 8, height: 12))
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 8, y: 20))
            p.addQuadCurve(to: CGPoint(x: 24, y: 20), control: CGPoint(x: 16, y: 26))
            p.addQuadCurve(to: CGPoint(x: 40, y: 20), control: CGPoint(x: 32, y: 26))
            },
                  stroke: Theme.led,
                  fill: nil,
                  width: 2,
                  cap: .butt,
                  join: .miter),
        ])
        case .topologia: (48, [
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 19, y: 5, width: 10, height: 10))
            },
                  stroke: nil,
                  fill: Theme.led,
                  width: 1,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 5, y: 25, width: 10, height: 10))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 19, y: 33, width: 10, height: 10))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 33, y: 25, width: 10, height: 10))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 21, y: 14))
            p.addLine(to: CGPoint(x: 12, y: 26))
            p.move(to: CGPoint(x: 24, y: 15))
            p.addLine(to: CGPoint(x: 24, y: 33))
            p.move(to: CGPoint(x: 27, y: 14))
            p.addLine(to: CGPoint(x: 36, y: 26))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2,
                  cap: .butt,
                  join: .miter),
        ])
        case .perfil: (48, [
            Layer(path: Path { p in
            p.addEllipse(in: CGRect(x: 16, y: 9, width: 16, height: 16))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .butt,
                  join: .miter),
            Layer(path: Path { p in
            p.move(to: CGPoint(x: 8, y: 42))
            p.addCurve(to: CGPoint(x: 40, y: 42), control1: CGPoint(x: 8, y: 30), control2: CGPoint(x: 40, y: 30))
            },
                  stroke: Theme.text2,
                  fill: nil,
                  width: 2.5,
                  cap: .round,
                  join: .miter),
        ])
        case .chat: (TaylorMark.side, TaylorMark.layers)
        }
    }
}

/// The Bridge mark, from `BRIDGE_MARK` in the prototype.
public struct BridgeMark: View {
    public var size: CGFloat = 40
    public init(size: CGFloat = 40) { self.size = size }

    public var body: some View {
        Canvas { context, bounds in
            let s = min(bounds.width, bounds.height) / Self.side
            let transform = CGAffineTransform(scaleX: s, y: s)
            for layer in Self.layers {
                let path = layer.path.applying(transform)
                if let fill = layer.fill { context.fill(path, with: .color(fill)) }
                if let stroke = layer.stroke {
                    context.stroke(path, with: .color(stroke),
                                   style: StrokeStyle(lineWidth: layer.width * s,
                                                      lineCap: layer.cap,
                                                      lineJoin: layer.join))
                }
            }
        }
        .frame(width: size, height: size)
        .accessibilityLabel("Bridge")
    }

    static let side: CGFloat = 64
    typealias Layer = BridgeIcon.Layer
    static let layers: [Layer] = [
        Layer(path: Path { p in
        p.addRoundedRect(in: CGRect(x: 4, y: 4, width: 56, height: 56), cornerSize: CGSize(width: 14, height: 14))
        },
              stroke: Theme.accent,
              fill: Theme.surface2,
              width: 3,
              cap: .butt,
              join: .miter),
        Layer(path: Path { p in
        p.move(to: CGPoint(x: 12, y: 44))
        p.addLine(to: CGPoint(x: 12, y: 30))
        p.move(to: CGPoint(x: 52, y: 44))
        p.addLine(to: CGPoint(x: 52, y: 30))
        },
              stroke: Theme.led,
              fill: nil,
              width: 4,
              cap: .round,
              join: .miter),
        Layer(path: Path { p in
        p.move(to: CGPoint(x: 8, y: 30))
        p.addQuadCurve(to: CGPoint(x: 56, y: 30), control: CGPoint(x: 32, y: 10))
        },
              stroke: Theme.led,
              fill: nil,
              width: 4,
              cap: .round,
              join: .miter),
        Layer(path: Path { p in
        p.move(to: CGPoint(x: 8, y: 44))
        p.addLine(to: CGPoint(x: 56, y: 44))
        },
              stroke: Theme.power,
              fill: nil,
              width: 4,
              cap: .round,
              join: .miter),
        Layer(path: Path { p in
        p.move(to: CGPoint(x: 22, y: 44))
        p.addLine(to: CGPoint(x: 22, y: 36))
        p.move(to: CGPoint(x: 32, y: 44))
        p.addLine(to: CGPoint(x: 32, y: 33))
        p.move(to: CGPoint(x: 42, y: 44))
        p.addLine(to: CGPoint(x: 42, y: 36))
        },
              stroke: Theme.led,
              fill: nil,
              width: 3,
              cap: .round,
              join: .miter),
        Layer(path: Path { p in
        p.addEllipse(in: CGRect(x: 52.5, y: 40.5, width: 7, height: 7))
        },
              stroke: nil,
              fill: Theme.power,
              width: 1,
              cap: .butt,
              join: .miter),
    ]
}

/// The Taylor mark, from `TAYLOR_MARK` in the prototype.
public struct TaylorMark: View {
    public var size: CGFloat = 40
    public init(size: CGFloat = 40) { self.size = size }

    public var body: some View {
        Canvas { context, bounds in
            let s = min(bounds.width, bounds.height) / Self.side
            let transform = CGAffineTransform(scaleX: s, y: s)
            for layer in Self.layers {
                let path = layer.path.applying(transform)
                if let fill = layer.fill { context.fill(path, with: .color(fill)) }
                if let stroke = layer.stroke {
                    context.stroke(path, with: .color(stroke),
                                   style: StrokeStyle(lineWidth: layer.width * s,
                                                      lineCap: layer.cap,
                                                      lineJoin: layer.join))
                }
            }
        }
        .frame(width: size, height: size)
        .accessibilityLabel("Taylor")
    }

    static let side: CGFloat = 64
    typealias Layer = BridgeIcon.Layer
    static let layers: [Layer] = [
        Layer(path: Path { p in
        p.addEllipse(in: CGRect(x: 3, y: 3, width: 58, height: 58))
        },
              stroke: Theme.accent,
              fill: Theme.surface2,
              width: 3,
              cap: .butt,
              join: .miter),
        Layer(path: Path { p in
        p.move(to: CGPoint(x: 14, y: 22))
        p.addLine(to: CGPoint(x: 40, y: 22))
        },
              stroke: Theme.led,
              fill: nil,
              width: 4,
              cap: .round,
              join: .miter),
        Layer(path: Path { p in
        p.move(to: CGPoint(x: 27, y: 22))
        p.addLine(to: CGPoint(x: 27, y: 48))
        },
              stroke: Theme.led,
              fill: nil,
              width: 4,
              cap: .round,
              join: .miter),
        Layer(path: Path { p in
        p.move(to: CGPoint(x: 40, y: 22))
        p.addLine(to: CGPoint(x: 45, y: 27))
        p.addLine(to: CGPoint(x: 49, y: 19))
        p.addLine(to: CGPoint(x: 53, y: 24))
        },
              stroke: Theme.power,
              fill: nil,
              width: 3,
              cap: .round,
              join: .round),
        Layer(path: Path { p in
        p.addEllipse(in: CGRect(x: 50, y: 21, width: 6, height: 6))
        },
              stroke: nil,
              fill: Theme.power,
              width: 1,
              cap: .butt,
              join: .miter),
    ]
}

extension Path {
    /// SVG's elliptical arc, which SwiftUI has no direct equivalent for.
    ///
    /// Implemented by centre-parameterisation per the SVG specification, appendix
    /// F.6. The prototype uses it for the storage cylinder and the chain links.
    mutating func addSVGArc(from: CGPoint, to: CGPoint, rx: CGFloat, ry: CGFloat,
                            rotation: CGFloat, largeArc: Bool, sweep: Bool) {
        guard rx != 0, ry != 0 else { addLine(to: to); return }
        let phi = rotation * .pi / 180
        let dx2 = (from.x - to.x) / 2, dy2 = (from.y - to.y) / 2
        let x1 =  cos(phi) * dx2 + sin(phi) * dy2
        let y1 = -sin(phi) * dx2 + cos(phi) * dy2
        var rx = abs(rx), ry = abs(ry)
        let lambda = (x1 * x1) / (rx * rx) + (y1 * y1) / (ry * ry)
        if lambda > 1 { rx *= sqrt(lambda); ry *= sqrt(lambda) }
        let sign: CGFloat = largeArc == sweep ? -1 : 1
        let num = max(0, rx*rx * ry*ry - rx*rx * y1*y1 - ry*ry * x1*x1)
        let den = rx*rx * y1*y1 + ry*ry * x1*x1
        let coef = sign * sqrt(den == 0 ? 0 : num / den)
        let cx1 =  coef * rx * y1 / ry
        let cy1 = -coef * ry * x1 / rx
        let cx = cos(phi) * cx1 - sin(phi) * cy1 + (from.x + to.x) / 2
        let cy = sin(phi) * cx1 + cos(phi) * cy1 + (from.y + to.y) / 2
        let start = atan2((y1 - cy1) / ry, (x1 - cx1) / rx)
        let end   = atan2((-y1 - cy1) / ry, (-x1 - cx1) / rx)
        var delta = end - start
        if !sweep && delta > 0 { delta -= 2 * .pi }
        if sweep && delta < 0 { delta += 2 * .pi }
        var transform = CGAffineTransform(translationX: cx, y: cy)
            .rotated(by: phi)
            .scaledBy(x: rx, y: ry)
        addArc(center: .zero, radius: 1, startAngle: .radians(start),
               endAngle: .radians(start + delta), clockwise: delta < 0,
               transform: transform)
    }
}
