// Generated by tools/extract_roles.py from source/Bridge_RC2_1.html
// Bridge RC2.1 · do not edit by hand; re-run `tools/extract_all.sh` instead.
// The prototype is the canon. This file is its shadow.


/// Who may see and change what.
///
/// Screens absent from a role are hidden, not disabled. Mutating controls
/// render disabled when `canWrite` is false. Identity arrives as OIDC claims
/// in production; the picker on the front door is the demo stand-in.
public enum Role: String, CaseIterable, Sendable, Codable {
    case admin
    case enterprise
    case `operator`
    case auditor
    case reception

    /// String-catalog key for this role's display name.
    public var labelKey: String {
        switch self {
        case .admin: "role_admin"
        case .enterprise: "role_enterprise"
        case .`operator`: "role_operator"
        case .auditor: "role_auditor"
        case .reception: "role_reception"
        }
    }

    /// May this role change records?
    public var canWrite: Bool {
        switch self {
        case .admin: true
        case .enterprise: true
        case .`operator`: true
        case .auditor: false
        case .reception: false
        }
    }

    /// Administrative roles reach the wizard and the policy editor.
    public var isAdmin: Bool { self == .admin || self == .enterprise }

    /// The screens this role may open, in sidebar order.
    public var screens: [Screen] {
        switch self {
        // Sees every screen and may change records; the wizard and the policies are theirs.
        case .admin: [.home, .cobranza, .facturas, .agentes, .modelos, .catalogo, .configuracion, .cadena, .datos, .chat, .salud, .energia, .integraciones, .ajustes, .incidentes, .actualizar, .auditoria, .perfil]
        // Everything Admin sees plus the Enterprise group: supplier match, measures, stores, topology.
        case .enterprise: [.home, .conciliacion, .medidas, .tiendas, .topologia, .cobranza, .facturas, .agentes, .modelos, .catalogo, .configuracion, .cadena, .datos, .chat, .salud, .energia, .integraciones, .ajustes, .incidentes, .actualizar, .auditoria, .perfil]
        // The working roles: collections, invoices, agents, incidents.
        case .`operator`: [.home, .cobranza, .facturas, .agentes, .catalogo, .configuracion, .chat, .salud, .energia, .incidentes, .perfil]
        // Reads everything that carries evidence; changes nothing.
        case .auditor: [.home, .cadena, .datos, .salud, .auditoria, .perfil]
        // The front desk: health, agents, chat, profile. Nothing financial.
        case .reception: [.home, .chat, .perfil]
        }
    }

    /// Hidden, not greyed: the sidebar never advertises a screen the role cannot open.
    public func canOpen(_ screen: Screen) -> Bool { screens.contains(screen) }
}
