// Generated by tools/extract_schema.py from source/Bridge_RC2_1.html
// Bridge RC2.1 · do not edit by hand; re-run `tools/extract_all.sh` instead.
// The prototype is the canon. This file is its shadow.


import Foundation
import SwiftData

/// The 25 document stores, typed.
///
/// The prototype keeps schemaless documents in IndexedDB, so these shapes are
/// inferred from what `seed()` actually produces. A field that only some records
/// carry is optional here, which is the honest reading; a field no seeded record
/// carries cannot be inferred at all, and those stores are marked below.
///
/// `id` is the key path in every store, matching the prototype's `keyPath: "id"`.

/// Collections accounts: who is being chased, for what, and when next.
/// Seeded with 6 records.
@Model
public final class Account {
    @Attribute(.unique) public var id: String
    public var name: String
    public var uuid: String
    public var next: String
    public var status: String
    public var touchesToday: Int
    public var paused: Bool
    public var escalated: Bool
    public var history: [String]

    public init(id: String, name: String, uuid: String, next: String, status: String, touchesToday: Int, paused: Bool, escalated: Bool, history: [String]) {
        self.id = id
        self.name = name
        self.uuid = uuid
        self.next = next
        self.status = status
        self.touchesToday = touchesToday
        self.paused = paused
        self.escalated = escalated
        self.history = history
    }
}

/// CFDI invoices through the five stages, with their REP clocks.
/// Seeded with 83 records.
@Model
public final class Invoice {
    @Attribute(.unique) public var id: String
    public var uuid: String
    public var client: String
    public var stage: String
    public var amount: Int
    public var issued: String
    public var repDay: Int
    public var supplier: String?   // 40/83 records
    public var type: String?   // 40/83 records
    public var method: String?   // 40/83 records
    public var qty: Int?   // 40/83 records
    public var price: Int?   // 40/83 records
    public var rfc: String?   // 40/83 records
    public var sat: String?   // 40/83 records
    public var po: String?   // 40/83 records
    public var cancel: Data?   // 2/83 records

    public init(id: String, uuid: String, client: String, stage: String, amount: Int, issued: String, repDay: Int, supplier: String? = nil, type: String? = nil, method: String? = nil, qty: Int? = nil, price: Int? = nil, rfc: String? = nil, sat: String? = nil, po: String? = nil, cancel: Data? = nil) {
        self.id = id
        self.uuid = uuid
        self.client = client
        self.stage = stage
        self.amount = amount
        self.issued = issued
        self.repDay = repDay
        self.supplier = supplier
        self.type = type
        self.method = method
        self.qty = qty
        self.price = price
        self.rfc = rfc
        self.sat = sat
        self.po = po
        self.cancel = cancel
    }
}

/// The agent roster: scope, guardrails version, status, counts.
/// Seeded with 5 records.
@Model
public final class Agent {
    @Attribute(.unique) public var id: String
    public var name: String
    public var kind: String
    public var count: Int
    public var status: String
    public var version: Int
    public var tone: String
    public var limits: String
    public var publishedAt: String

    public init(id: String, name: String, kind: String, count: Int, status: String, version: Int, tone: String, limits: String, publishedAt: String) {
        self.id = id
        self.name = name
        self.kind = kind
        self.count = count
        self.status = status
        self.version = version
        self.tone = tone
        self.limits = limits
        self.publishedAt = publishedAt
    }
}

/// Models installed on the cluster.
/// Seeded with 4 records.
@Model
public final class InstalledModel {
    @Attribute(.unique) public var id: String
    public var name: String
    public var version: String
    public var status: String
    public var history: [String]
    public var activatedAt: String

    public init(id: String, name: String, version: String, status: String, history: [String], activatedAt: String) {
        self.id = id
        self.name = name
        self.version = version
        self.status = status
        self.history = history
        self.activatedAt = activatedAt
    }
}

/// The sealed chain. Append-only; see CanonicalSeal.
/// Seeded with 3 records.
@Model
public final class LedgerEntry {
    @Attribute(.unique) public var id: String
    public var seq: Int
    public var at: String
    public var actor: String
    public var es: String
    public var en: String
    public var key: String
    public var prevHash: String
    public var hash: String

    public init(id: String, seq: Int, at: String, actor: String, es: String, en: String, key: String, prevHash: String, hash: String) {
        self.id = id
        self.seq = seq
        self.at = at
        self.actor = actor
        self.es = es
        self.en = en
        self.key = key
        self.prevHash = prevHash
        self.hash = hash
    }
}

/// Cluster nodes: role, temperature, memory, status.
/// Seeded with 17 records.
@Model
public final class ClusterNode {
    @Attribute(.unique) public var id: String
    public var role: String
    public var status: String
    public var tempC: Int
    public var memGB: Int
    public var serial: String
    public var ledger: String

    public init(id: String, role: String, status: String, tempC: Int, memGB: Int, serial: String, ledger: String) {
        self.id = id
        self.role = role
        self.status = status
        self.tempC = tempC
        self.memGB = memGB
        self.serial = serial
        self.ledger = ledger
    }
}

/// The power spine: solar, battery, grid, islanding.
/// Seeded with 1 record.
@Model
public final class PowerState {
    @Attribute(.unique) public var id: String
    public var solarKW: Double
    public var batteryPct: Int
    public var grid: String
    public var islanded: Bool
    public var reservePct: Int
    public var curtail: Bool
    public var upsMin: Int

    public init(id: String, solarKW: Double, batteryPct: Int, grid: String, islanded: Bool, reservePct: Int, curtail: Bool, upsMin: Int) {
        self.id = id
        self.solarKW = solarKW
        self.batteryPct = batteryPct
        self.grid = grid
        self.islanded = islanded
        self.reservePct = reservePct
        self.curtail = curtail
        self.upsMin = upsMin
    }
}

/// Update channel state and history.
/// Seeded with 1 record.
@Model
public final class Update {
    @Attribute(.unique) public var id: String
    public var version: String
    public var stage: Int
    public var paused: Bool
    public var history: [String]

    public init(id: String, version: String, stage: Int, paused: Bool, history: [String]) {
        self.id = id
        self.version = version
        self.stage = stage
        self.paused = paused
        self.history = history
    }
}

/// People with a login and a role.
/// Seeded with 4 records.
@Model
public final class User {
    @Attribute(.unique) public var id: String
    public var name: String
    public var role: String
    public var createdAt: String

    public init(id: String, name: String, role: String, createdAt: String) {
        self.id = id
        self.name = name
        self.role = role
        self.createdAt = createdAt
    }
}

/// Console settings, one record.
/// Seeded with 1 record.
@Model
public final class SettingsRecord {
    @Attribute(.unique) public var id: String
    public var guardrailsVersion: String
    public var termsVersion: String
    public var humanApproval: Bool
    public var batchesOnRequest: Bool

    public init(id: String, guardrailsVersion: String, termsVersion: String, humanApproval: Bool, batchesOnRequest: Bool) {
        self.id = id
        self.guardrailsVersion = guardrailsVersion
        self.termsVersion = termsVersion
        self.humanApproval = humanApproval
        self.batchesOnRequest = batchesOnRequest
    }
}

/// Configured connectors, by family.
/// Seeded with 1 record.
@Model
public final class Integration {
    @Attribute(.unique) public var id: String
    public var family: String
    public var template: String
    public var name: String
    public var status: String
    public var endpoint: String
    public var lastTest: String
    public var fields: Data
    public var mapping: Data
    public var createdAt: String

    public init(id: String, family: String, template: String, name: String, status: String, endpoint: String, lastTest: String, fields: Data, mapping: Data, createdAt: String) {
        self.id = id
        self.family = family
        self.template = template
        self.name = name
        self.status = status
        self.endpoint = endpoint
        self.lastTest = lastTest
        self.fields = fields
        self.mapping = mapping
        self.createdAt = createdAt
    }
}

/// Installer progress and findings.
/// Seeded with 1 record.
@Model
public final class InstallerState {
    @Attribute(.unique) public var id: String
    public var step: Int
    public var done: Bool

    public init(id: String, step: Int, done: Bool) {
        self.id = id
        self.step = step
        self.done = done
    }
}

/// Guardrails, terms of service, terms of use; versioned with a diff.
/// Seeded with 4 records.
@Model
public final class Policy {
    @Attribute(.unique) public var id: String
    public var version: String
    public var lang: String
    public var text: String
    public var hash: String
    public var publishedAt: String
    public var publishedBy: String
    public var history: [String]

    public init(id: String, version: String, lang: String, text: String, hash: String, publishedAt: String, publishedBy: String, history: [String]) {
        self.id = id
        self.version = version
        self.lang = lang
        self.text = text
        self.hash = hash
        self.publishedAt = publishedAt
        self.publishedBy = publishedBy
        self.history = history
    }
}

/// Suppliers behind the supplier-match case model.
/// Seeded with 6 records.
@Model
public final class Supplier {
    @Attribute(.unique) public var id: String
    public var name: String
    public var rfc: String
    public var status: String
    public var terms: Int
    public var openCases: Int

    public init(id: String, name: String, rfc: String, status: String, terms: Int, openCases: Int) {
        self.id = id
        self.name = name
        self.rfc = rfc
        self.status = status
        self.terms = terms
        self.openCases = openCases
    }
}

/// Purchase orders: what was authorized.
/// Seeded with 40 records.
@Model
public final class PurchaseOrder {
    @Attribute(.unique) public var id: String
    public var supplier: String
    public var date: String
    public var qty: Int
    public var price: Int
    public var total: Int

    public init(id: String, supplier: String, date: String, qty: Int, price: Int, total: Int) {
        self.id = id
        self.supplier = supplier
        self.date = date
        self.qty = qty
        self.price = price
        self.total = total
    }
}

/// Receiving records: what arrived.
/// Seeded with 40 records.
@Model
public final class ReceivingRecord {
    @Attribute(.unique) public var id: String
    public var po: String
    public var date: String
    public var qty: Int
    public var dc: String

    public init(id: String, po: String, date: String, qty: Int, dc: String) {
        self.id = id
        self.po = po
        self.date = date
        self.qty = qty
        self.dc = dc
    }
}

/// Bank records: what was paid.
/// Seeded with 20 records.
@Model
public final class BankRecord {
    @Attribute(.unique) public var id: String
    public var invoice: String
    public var date: String
    public var amount: Int
    public var reference: String

    public init(id: String, invoice: String, date: String, amount: Int, reference: String) {
        self.id = id
        self.invoice = invoice
        self.date = date
        self.amount = amount
        self.reference = reference
    }
}

/// The owning case per cross-store exception. One owner, always.
/// Seeded with 3 records.
@Model
public final class MatchCase {
    @Attribute(.unique) public var id: String
    public var invoice: String
    public var po: String
    public var supplier: String
    public var status: String
    public var title: String
    public var owner: String
    public var opened: String
    public var minutes: Int
    public var agent: String
    public var actions: [String]
    public var finding: String

    public init(id: String, invoice: String, po: String, supplier: String, status: String, title: String, owner: String, opened: String, minutes: Int, agent: String, actions: [String], finding: String) {
        self.id = id
        self.invoice = invoice
        self.po = po
        self.supplier = supplier
        self.status = status
        self.title = title
        self.owner = owner
        self.opened = opened
        self.minutes = minutes
        self.agent = agent
        self.actions = actions
        self.finding = finding
    }
}

/// OXXO stores and their connector state.
/// Seeded with 12 records.
@Model
public final class StoreSite {
    @Attribute(.unique) public var id: String
    public var name: String
    public var city: String
    public var dc: String
    public var site: String
    public var connector: String
    public var queued: Int
    public var openCases: Int
    public var agent: String
    public var planogram: String?   // 0/12 records
    public var tickets: Int

    public init(id: String, name: String, city: String, dc: String, site: String, connector: String, queued: Int, openCases: Int, agent: String, planogram: String? = nil, tickets: Int) {
        self.id = id
        self.name = name
        self.city = city
        self.dc = dc
        self.site = site
        self.connector = connector
        self.queued = queued
        self.openCases = openCases
        self.agent = agent
        self.planogram = planogram
        self.tickets = tickets
    }
}

/// Sites in the topology: core, recovery, regional, South America.
/// Seeded with 15 records.
@Model
public final class Site {
    @Attribute(.unique) public var id: String
    public var name: String
    public var city: String
    public var kind: String
    public var nodes: Int
    public var octets: Int
    public var stores: Int
    public var queued: Int
    public var lag: Int
    public var latency: Int

    public init(id: String, name: String, city: String, kind: String, nodes: Int, octets: Int, stores: Int, queued: Int, lag: Int, latency: Int) {
        self.id = id
        self.name = name
        self.city = city
        self.kind = kind
        self.nodes = nodes
        self.octets = octets
        self.stores = stores
        self.queued = queued
        self.lag = lag
        self.latency = latency
    }
}

/// The topology view's own state.
/// Seeded with 1 record.
@Model
public final class TopologyState {
    @Attribute(.unique) public var id: String
    public var view: String

    public init(id: String, view: String) {
        self.id = id
        self.view = view
    }
}

// MARK: - Stores the seed does not populate
//
// These exist in the prototype's STORES list but hold nothing after seeding,
// so there is no shape to infer. They are written by the running app, and
// each needs its schema taken from the code that writes it:
//   incidents    -> Incident         Open and closed incidents.
//   chat         -> ChatTurn         Chat turns.
//   jobs         -> Job              Background jobs.
//   chats        -> ChatThread       Chat threads, as distinct from their turns.

/// Every model in the store, for the SwiftData container.
public enum BridgeSchema {
    public static let models: [any PersistentModel.Type] = [
        Account.self,
        Invoice.self,
        Agent.self,
        InstalledModel.self,
        LedgerEntry.self,
        ClusterNode.self,
        PowerState.self,
        Update.self,
        User.self,
        SettingsRecord.self,
        Integration.self,
        InstallerState.self,
        Policy.self,
        Supplier.self,
        PurchaseOrder.self,
        ReceivingRecord.self,
        BankRecord.self,
        MatchCase.self,
        StoreSite.self,
        Site.self,
        TopologyState.self,
    ]
}
