#!/usr/bin/env python3
"""
Seed.json -> Seed.client.json

Daniel's section 7 forbids node counts, model names, bills of materials and
prices from reaching a client before a signed discovery agreement. RC2 answers
that with a demo mode, and a demo mode implemented as a runtime toggle leaves
every one of those figures sitting in the binary — one flag away from a screen,
and one mistake away from a room.

So the client build gets a different seed. The names are not hidden in it; they
are not in it. `tools/make_client_build.sh` swaps this file in before archiving,
and `DemoModeTests` fails if a forbidden string survives the swap.

What stays: the shape. Same record count, same ids, same relationships, so every
screen renders identically and the demo is a demo of the real console.
"""

import json, os, re, sys

SOURCE = "Bridge/Sources/BridgeKit/Resources/Seed.json"
OUT = "Bridge/Sources/BridgeKit/Resources/Seed.client.json"

# Model families that must not appear. Matched case-insensitively, as whole
# words, anywhere in any string value.
MODEL_NAMES = ["kimi", "llama", "qwen", "deepseek", "mistral", "gpt", "claude",
               "gemini", "moonshot", "k2", "k3"]

# What a client sees instead. The brief names these two.
ESCALATION = ("escalation model", "modelo de escalación")
ROUTINE = ("routine model", "modelo de rutina")

# Roles carry model names; these are the replacements, by what the role does.
ROLE_MAP = {
    "kimi shard": "escalation model shard",
    "llama 4": "routine model",
    "llama": "routine model",
    "replica": "replica",
    "admin + spare": "admin + spare",
}


def redact_role(role):
    low = role.lower()
    for needle, replacement in ROLE_MAP.items():
        if needle in low:
            return replacement
    return role


def redact_text(text):
    """Replace a model family name wherever it appears in free text."""
    out = text
    for name in MODEL_NAMES:
        out = re.sub(rf"\b{re.escape(name)}\b[\w.\-]*", ROUTINE[0], out, flags=re.IGNORECASE)
    return out


def contains_model_name(text):
    return any(re.search(rf"\b{re.escape(n)}\b", text, re.IGNORECASE) for n in MODEL_NAMES)


def walk(value, key=None):
    if isinstance(value, dict):
        return {k: walk(v, k) for k, v in value.items()}
    if isinstance(value, list):
        return [walk(v) for v in value]
    if isinstance(value, str):
        if key == "role":
            return redact_role(value)
        if contains_model_name(value):
            return redact_text(value)
        return value
    return value


def main():
    with open(SOURCE, encoding="utf-8") as fh:
        seed = json.load(fh)

    redacted = walk(seed)
    redacted["note"] = ("Client demo seed. Generated by tools/redact_seed.py. Model names are "
                        "absent rather than hidden; see docs/DEMO_MODE.md.")

    # Prove it before writing it. A redactor that silently misses something is
    # worse than no redactor, because somebody will trust it.
    text = json.dumps(redacted, ensure_ascii=False)
    leaks = sorted({n for n in MODEL_NAMES
                    if re.search(rf"\b{re.escape(n)}\b", text, re.IGNORECASE)})
    if leaks:
        print(f"redact: FAILED — these names survive redaction: {', '.join(leaks)}")
        for name in leaks:
            for match in re.finditer(rf'"[^"]*\b{re.escape(name)}\b[^"]*"', text, re.IGNORECASE):
                print(f"    {match.group(0)[:100]}")
                break
        return 1

    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(redacted, fh, ensure_ascii=False, indent=2)
        fh.write("\n")

    stores = {k: len(v) for k, v in redacted.items() if isinstance(v, list)}
    original = {k: len(v) for k, v in seed.items() if isinstance(v, list)}
    if stores != original:
        print(f"redact: FAILED — record counts changed. The client build must show the same "
              f"console, not a smaller one.")
        return 1

    changed = sum(1 for a, b in zip(json.dumps(seed, sort_keys=True).splitlines(),
                                    json.dumps(redacted, sort_keys=True).splitlines()) if a != b)
    print(f"redact: {sum(stores.values())} records across {len(stores)} stores -> {OUT}")
    print(f"        no model name survives; record counts unchanged")
    roles = sorted({n.get("role", "") for n in redacted.get("nodes", [])})
    print(f"        node roles now: {', '.join(roles)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
