// Generated by tools/extract_routes.py from source/Bridge_RC2_1.html
// Bridge RC2.1 · do not edit by hand; re-run `tools/extract_all.sh` instead.
// The prototype is the canon. This file is its shadow.


import Foundation

/// Every screen Bridge can route to.
///
/// The raw value is the prototype's route name and is load-bearing: it keys the
/// string catalog (`nav_<raw>`), the icon set, and the seeded ledger. Registered
/// in four places in the prototype — the object literal, three `Object.assign`
/// blocks and ten direct assignments — so this list is the union of all four.
public enum Screen: String, CaseIterable, Sendable, Codable {
    case actualizar
    case agente
    case agentes
    case ajustes
    case auditoria
    case baterias
    case cadena
    case caso
    case catalogo
    case chat
    case cobranza
    case conciliacion
    case conectar
    case configuracion
    case cuenta
    case datos
    case energia
    case evento
    case factura
    case facturas
    case home
    case incidente
    case incidentes
    case installer
    case integracion
    case integraciones
    case login
    case medidas
    case modelo
    case modelos
    case nodo
    case perfil
    case politicas
    case red
    case salud
    case sitio
    case solar
    case studio
    case tienda
    case tiendas
    case topologia
    case ups
    case usuario

    /// Detail screens carry a record id; landing screens do not.
    public var takesRecord: Bool {
        switch self {
        case .agente, .caso, .conectar, .cuenta, .evento, .factura, .incidente, .integracion, .modelo, .nodo, .sitio, .tienda, .usuario: true
        default: false
        }
    }

    /// The label this screen shows in a breadcrumb trail.
    ///
    /// Detail screens carry their own short label; everything else falls back to
    /// its sidebar name.
    public var crumbLabel: String {
        switch self {
        case .agente: L("Agent")
        case .baterias: L("Batteries")
        case .caso: L("Case (label)")
        case .conectar: L("Connect")
        case .cuenta: L("Account")
        case .evento: L("Event")
        case .factura: L("Invoice")
        case .incidente: L("Incident")
        case .integracion: L("API")
        case .modelo: L("Model")
        case .nodo: L("Node")
        case .politicas: L("Policies")
        case .red: L("Grid")
        case .sitio: L("Site")
        case .solar: L("Solar")
        case .studio: L("AgentStudio")
        case .tienda: L("Store")
        case .ups: L("UPS")
        case .usuario: L("User")
        default: Key(rawValue: "nav_\(rawValue)")?.string ?? rawValue
        }
    }
}

/// One place in the navigation stack: a screen, and the record it is showing.
public struct Route: Hashable, Sendable, Codable {
    public var screen: Screen
    public var recordID: String?

    public init(_ screen: Screen, _ recordID: String? = nil) {
        self.screen = screen
        self.recordID = recordID
    }

    /// The prototype's `data-open="route:id"` form, which the ledger also records.
    public var token: String { recordID.map { "\(screen.rawValue):\($0)" } ?? screen.rawValue }

    public init?(token: String) {
        let parts = token.split(separator: ":", maxSplits: 1)
        guard let screen = Screen(rawValue: String(parts[0])) else { return nil }
        self.init(screen, parts.count > 1 ? String(parts[1]) : nil)
    }
}
